[package]
name = "camper-diff"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
itertools = "0.11.0"

[[bin]]
path="src/main.rs"
name="cdiff"
