[package]
name = "camper-diff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
diff = "0.1.13"

[[bin]]
path="src/main.rs"
name="cdiff"
